name: Build and Push Container with nightly tag on any push to non-main branch

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build-and-push-nightly:
    runs-on: docker
    steps:
      - name: Local container push
        uses: https://git.mro.land/actions/local-container-push@v1
        with:
          tag: nightly
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

